package.json

chore: fix typo

---

Containerfile

fix: Add icon to OCI image

---

vite.config.js

Mark @kubernetes/client-node as external, the same way podman-desktop does

---

src/extension.ts

Add delete implementation and refactor updating status to avoid extra UI updates

---

.extfiles
package.json
scripts/build.js
vite.config.js
yarn.lock

Update build.js script to bundle only required files into ext archive

---

package.json
src/kubeconfig.ts
yarn.lock

Ensure the kubeconfig file exists before writing to it

---

yarn.lock

Update yarn.lock file from scratch to use yarnpkg.com only

---

package.json

Remove 'OpenShft Developer Sandbox' from property names

---

package.json

Add explanation how to fill up 'Login command' field to create connection form

---

src/extension.ts

Dispose active connections on deactivation even

---

package.json

Update description for Context name property

---

package.json
src/extension.ts

Update links to sandbox to use marketing campaign id

---

package.json
src/extension.ts
src/podman-cli.ts
yarn.lock

Fix #67.
https://github.com/redhat-developer/podman-desktop-sandbox-ext/assets/620330/624e93e4-1991-4eb6-933a-d6c1e339d366

Add 'Push image to Developer Sandbox cluster' command for images

---

src/extension.ts

Calculate namespace for sandbox context using ${username}-dev template

---

src/podman-cli.ts

Add proxy env vars for podman execution when proxy is enabled

---

package.json

chore: Fix yarn build

---

.github/workflows/pr-check.yaml
.prettierrc
package.json
scripts/build.js
src/extension.ts
src/kubeconfig.ts
src/podman-cli.ts
yarn.lock

chore: Setup Prettier

---

package.json
src/extension.ts

fix: add 'Set as default context' option when creating sandbox connection

---

package.json

fix: add default value for sandbox context name

---

src/extension.ts

Fix https://github.com/containers/podman-desktop/issues/5154

fix: add sandbox.open.login.url command disposable to subscriptions

---

README.md

Add Usage and Installation sections to README.md

---

.github/workflows/ci.yaml
.github/workflows/pr-check.yaml
.github/workflows/release.yaml

chore: update to Node 20

---

.extfiles

related to https://github.com/containers/podman-desktop/issues/7363

chore: include README.md file inside the extension

---

src/extension.spec.ts
src/extension.ts
src/openshift.ts

fix: set current context to new sandbox-context

---

package.json
scripts/build.cjs

Issue: https://github.com/redhat-developer/podman-desktop-sandbox-ext/issues/219

Switch to ES modules

---

vite.config.js

fix: fix activation error

---

package.json

Update version to next 0.0.6 release.

fix: increment extension version to 0.0.6

---

.github/workflows/pr-check.yaml
.github/workflows/release.yaml

Update ubuntu version used in github actions to 24.04

fix(github-actions): update ubuntu to 24.04

---

.github/workflows/pr-check.yaml

Fixes: #496, most was done already in https://github.com/redhat-developer/podman-desktop-sandbox-ext/pull/500

chore(ci): update ubuntu runner in unit tests to 24.04

---

package.json
yarn.lock

chore(deps): remove electron dependency

---

.github/workflows/e2e-main.yaml

Issue: https://github.com/redhat-developer/podman-desktop-sandbox-ext/issues/647

chore(feat): Add e2e test production mode workflow
